#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Oct 19 20:21:48 2021

@author: maryamali
"""
#Boundary effect 

# blur ---------------------------------------
import matplotlib.pyplot
import random

data = []
processed_data = []

# Fill with random data.
for i in (range(0,99)):
    datarow = []
    for j in (range(0,99)):
        datarow.append(random.randint(0,255))
    data.append(datarow)

print ("len(data)", len(data))
print ("len(data[0])", len(data [0]))

# Blur.
for i in (range(0,98)):
    datarow = []
    for j in (range(0,98)):
        sum = data[i][j]
        sum += data[i-1][j]
        sum += data[i+1][j]
        print("i",i)
        print("j+1",j+1)
        sum += data[i][j+1]
        sum += data[i][j-1]
        sum /= 5
    datarow.append(sum)
    processed_data.append(datarow)

matplotlib.pyplot.imshow(data)
matplotlib.pyplot.show()
matplotlib.pyplot.imshow(processed_data)
matplotlib.pyplot.show()
